### ISSUE TITLE
Conversion to TypeScript and continued maintenance

### ISSUE THREAD

**Issue by mathew-kurian** [romanpolunin/OrgChart#7]
This isn't as much of an issue as much as a heads up. I have converted your c# modules to TypeScript and added a React component as an effort to make it easier to consume. Is this project in continued maintenance? If so, I can try to merge it in with the current project. Maybe once it's ready, we can think about it merging. Thoughts?

https://awesome-react-org-chart.vercel.app/example.html

Great library and I hope it has continued maintenance!

**Comment by mathew-kurian** [comment]
In addition, do you have idea why the aforementioned bug might be happening?

![image](https://user-images.githubusercontent.com/376453/88494081-f5336500-cf79-11ea-843a-4c9f2882903e.png)

**Comment by romanpolunin** [comment]
@mathew-kurian sorry for late response - looks like I missed the notification. The example page looks awesome, much better than my own sample page. As of the maintenance: as soon as anyone wants to use it, I'll help out. For me personally, this was a nice Christmas-time exercise a few years ago. If you report any bugs, I will either fix them myself or help you do so.

**Comment by romanpolunin** [comment]
And yes, please go ahead create pull requests or feature requests. I will look at your site closer as well.
