### ISSUE TITLE
Horizontal branch positions are wrong for specific box heights

### ISSUE THREAD

**Issue by harrymattison** [romanpolunin/OrgChart#9]
When I set the height of all boxes at 0.7, the CenterH of the BranchExterior elements is correct (they range from -0.625 to 0.625)

With different box height values (ranging from 0.67 to 0.69), the CenterH values are wrong (they have a much greater spread, ranging from -12.5 to 12.5)

When it works correctly, this breakpoint is hit once, `offense` is set to 1.25, i and k get incremented, then `ComputeOverlap` returns 1.25 because k = other.Left.Count = 1
![offense correct](https://github.com/romanpolunin/OrgChart/assets/2285720/6df8505f-0597-4ed5-a584-5026cdfe8991)

But when it does not work correctly, this breakpoint is hit twice. After the first time the breakpoint is hit, k does not get updated because my.Bottom = 1.84 and th.Bottom = 1.86. The second time the breakpoint is hit, my.X = 25, diff = 25, and offense gets set to 25.
![offense incorrect](https://github.com/romanpolunin/OrgChart/assets/2285720/ae4f40f8-8522-4237-a289-4a82dd3ce113)

I'd really appreciate it if you could fix this or point me in the right direction.
Thank you for developing and sharing this tool

**Comment by romanpolunin** [comment]
In order to reproduce, I would need to have the exact data for the boxes, and parameters you've used to configure layout algorithms. Some algorithms will produce different box positions when using same vs. different box heights. Can you maybe show me the screenshots with problematic layout results?

I have some problem with notifications from Github, didn't get the email when the issue was posted.

**Comment by harrymattison** [comment]
Is this the box and tree data you were asking for? I am using the Linear Layout Strategy as provided by this library.
[linearLayoutStrategy.json](https://github.com/romanpolunin/OrgChart/files/14352612/linearLayoutStrategy.json)
[state.json](https://github.com/romanpolunin/OrgChart/files/14352597/state.json)
[treeDrafting.json](https://github.com/romanpolunin/OrgChart/files/14352598/treeDrafting.json)

**Comment by romanpolunin** [comment]
The data says width of the boxes is like 50, whereas height is 0.25. The screenshot you attached does not show the actual box sizes, it renders circles. Maybe check the widths?

**Comment by romanpolunin** [comment]
Also try using the .NET desktop demo app to troubleshoot your layout. It is wired up with all visualization for troubleshooting already, should be easy to plug in your data and layout settings.

**Comment by romanpolunin** [comment]
<img width="1109" alt="image" src="https://github.com/romanpolunin/OrgChart/assets/12566205/66b96ad0-08c7-4507-a197-efc93806fb9e">

That's the best way to troubleshoot the layout ^^^ (OrgChart.CSharp.Test.App). It's quite old though, targets UWP.

**Comment by romanpolunin** [comment]
Closed since this layout result seems to be caused by box sizes, and not by any issues in the layout algorithm.
